name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec-pr-commenter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}